name       : libgaminggear
version    : 0.15.0
release    : 1
source     :
    - https://pilotfiber.dl.sourceforge.net/project/libgaminggear/libgaminggear-0.15.0.tar.bz2 : 0e4b15eeed529906b383750a346273c154822fe22d18b2f1b15a9e3851463884
license    : GPL-2.0
component  : desktop.library
summary    : Libgaminggear provides functions and widgets common for gaming input devices.
description: |
    Libgaminggear provides functions and widgets common for gaming input devices.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(sqlite3)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
