name       : libgaminggear
version    : 0.15.1
release    : 4
source     :
    - https://kent.dl.sourceforge.net/project/libgaminggear/libgaminggear-0.15.1.tar.bz2 : ffbd59c62e3107b09ec99f1e5147529c61931987abc7f86a140449b46388c549
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libgaminggear provides functions and widgets common for gaming input devices.
description: |
    Libgaminggear provides functions and widgets common for gaming input devices.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(sqlite3)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/usr/lib64/gaminggear_plugins
patterns   :
    - devel :
        - /usr/share/cmake-*
        - /usr/share/pkgconfig
